### ISSUE TITLE
goal_state is missing?

### ISSUE THREAD

**Issue by smirnp** [HAPILab/GoalAlignment#1]
Hello,

I'm trying to run the code and cannot do it because dependency to `goal_state` cannot be resolved. Is the file part of the repo?

Thank you!

**Comment by sarathsreedharan** [comment]
Hi,
Can you post the exact command you ran and the full error you got?

**Comment by smirnp** [comment]
I'm not even running it yet, just opened main.py in PyCharm and [`from goal_state import *`](https://github.com/HAPILab/GoalAlignment/blob/main/main.py#L1) PyCharm gives me `Unresolved reference` exception. Same also [here](https://github.com/HAPILab/GoalAlignment/blob/e1e580529e4396aaf14b20a45c741ea6a0c78ae7/fluent_prob.py#L7)


I guess it is one of the project files, which for some reasons didn't appear in the repo.

**Comment by sarathsreedharan** [comment]
Thanks, we will work on getting that fixed.

**Comment by Malek-Mechergui** [comment]
Hi, 
Thank you for pointing that out. The issue was fixed and the goal_state.py was uploaded.

**Comment by Malek-Mechergui** [comment]
Hi,
Thank you for pointing that out. The issue was fixed and the goal_state.py was uploaded.
